# Project-wide Gradle settings
org.gradle.jvmargs=-Xmx2048m -XX:MaxMetaspaceSize=512m
android.useAndroidX=true

# React Native flags
# New Architecture currently breaks Android CMake autolinking in this project
# because several dependencies do not generate the expected codegen JNI dirs.
newArchEnabled=false
hermesEnabled=true

# Only 64-bit ABIs
reactNativeArchitectures=arm64-v8a,x86_64

# NDK r28 (16 KB support)
# android.ndkVersion=28.0.12433566
android.ndkVersion=29.0.14206865
