import { StyleSheet } from 'react-native'

import { appPalette } from '@/shared/styles/appPalette'

export const graphStyles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: appPalette.surface,
  },
  content: {
    width: '100%',
    gap: 16,
    paddingTop: 16,
    paddingHorizontal: 16,
  },
  card: {
    width: '100%',
    overflow: 'hidden',
    borderRadius: 24,
    borderWidth: 1,
    borderColor: 'rgba(37, 18, 22, 0.08)',
    backgroundColor: '#FFFFFF',
    shadowColor: '#181114',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.08,
    shadowRadius: 20,
    elevation: 3,
  },
  hero: {
    gap: 18,
    paddingVertical: 22,
    paddingHorizontal: 18,
  },
  eyebrow: {
    color: 'rgba(66, 98, 125, 0.82)',
    fontFamily: 'Roboto-Bold',
    fontSize: 13,
    letterSpacing: 1.6,
    lineHeight: 18,
    textTransform: 'uppercase',
  },
  monthButton: {
    width: '100%',
    minHeight: 54,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
    paddingVertical: 12,
    paddingHorizontal: 18,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: appPalette.border,
    backgroundColor: '#FFFFFF',
    shadowColor: '#181114',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.05,
    shadowRadius: 12,
    elevation: 1,
  },
  monthButtonText: {
    minWidth: 0,
    flexShrink: 1,
    color: appPalette.primaryDark,
    fontFamily: 'Roboto-Bold',
    textAlign: 'center',
  },
  cardHeader: {
    minHeight: 80,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
    paddingTop: 20,
    paddingHorizontal: 18,
    paddingBottom: 16,
  },
  cardIcon: {
    width: 44,
    height: 44,
    flexShrink: 0,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 16,
    backgroundColor: appPalette.soft,
  },
  cardTitle: {
    minWidth: 0,
    flex: 1,
    color: '#1F1015',
    fontFamily: 'Roboto-Bold',
    fontSize: 23,
    lineHeight: 25,
  },
  tableShell: {
    paddingHorizontal: 18,
    paddingBottom: 18,
  },
  tableFrame: {
    overflow: 'hidden',
    borderRadius: 22,
    borderWidth: 1,
    borderColor: '#F0E9EC',
    backgroundColor: '#FFFFFF',
  },
  tableRow: {
    flexDirection: 'row',
  },
  tableCell: {
    minHeight: 48,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 12,
    paddingHorizontal: 14,
    borderBottomWidth: 1,
    borderRightWidth: 1,
    borderColor: '#F0EBED',
    backgroundColor: '#FFFFFF',
  },
  lastColumn: {
    borderRightWidth: 0,
  },
  lastRowCell: {
    borderBottomWidth: 0,
  },
  headCell: {
    backgroundColor: appPalette.soft,
  },
  headText: {
    color: 'rgba(68, 84, 97, 0.88)',
    fontFamily: 'Roboto-Bold',
    textAlign: 'center',
  },
  bodyText: {
    color: '#312126',
    fontFamily: 'Roboto-Medium',
    textAlign: 'center',
  },
  weekendCell: {
    backgroundColor: appPalette.surfaceAlt,
  },
  weekendText: {
    color: appPalette.brand,
  },
  todayCell: {
    backgroundColor: appPalette.softStrong,
    borderBottomColor: appPalette.primary,
    borderBottomWidth: 3,
  },
  currentUserCell: {
    backgroundColor: appPalette.soft,
  },
  currentUserNameCell: {
    backgroundColor: appPalette.softStrong,
    borderLeftWidth: 5,
    borderLeftColor: appPalette.primary,
  },
  currentUserText: {
    color: appPalette.primaryDeep,
    fontFamily: 'Roboto-Bold',
  },
  currentTodayCell: {
    backgroundColor: 'rgba(66, 98, 125, 0.22)',
  },
  filledHoursCell: {
    backgroundColor: appPalette.soft,
  },
  empty: {
    minHeight: 76,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 24,
    paddingHorizontal: 16,
    backgroundColor: '#FFFAFB',
  },
  emptyText: {
    color: 'rgba(84, 67, 73, 0.68)',
    fontFamily: 'Roboto-Medium',
    lineHeight: 22,
    textAlign: 'center',
  },
})
